server:
  port: 8080
spring:
  application:
    name: "TourDeFrance"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://mateo:EveIm6cb3tPF0qwr@tourdefrance.7xlvgx0.mongodb.net/?retryWrites=true&w=majority"
      database: "tourdefrance"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
